language: r
cache: packages
latex: false
fortran: false

matrix:
  include:
    - dist: xenial
    - os: osx
      brew_packages: apache-arrow
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true

addons:
  apt:
    update: true
    sources:
      - sourceline: 'deb [arch=amd64] http://dl.bintray.com/apache/arrow/ubuntu xenial main'
        key_url: 'https://dist.apache.org/repos/dist/dev/arrow/KEYS'
    packages: 'libarrow-dev libparquet-dev'
